services:
  api:
    container_name: shopper_api
    build: ./backend-nestjs
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    networks:
      - shopper_net
    env_file:
      - .env

  db:
    container_name: shopper_db
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: easyriderdb
    ports:
      - "5438:5432"
    restart: always
    networks:
      - shopper_net

networks:
  shopper_net:
    driver: bridge
