import type { Metadata } from "next";
import styles from './styles.module.sass'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={styles['app-layout-body']}>
        {children}
      </body>
    </html>
  );
}
